#
# This file is generated by ModusToolbox during the 'make getlibs' operation
# Any edits to this file will be lost the next time the library manager is run or
# the next time 'make getlibs' is run.
#
# List of local libraries



# The search paths for the included middleware
SEARCH_btstack-integration=../mtb_shared/btstack-integration/release-v6.2.1
SEARCH_kv-store=../mtb_shared/kv-store/release-v1.1.1
SEARCH_retarget-io=../mtb_shared/retarget-io/release-v1.8.1
SEARCH_serial-flash=../mtb_shared/serial-flash/release-v1.4.3
SEARCH_abstraction-rtos=../mtb_shared/abstraction-rtos/release-v1.12.0
SEARCH_btstack=../mtb_shared/btstack/release-v4.1.5
SEARCH_clib-support=../mtb_shared/clib-support/release-v1.8.0
SEARCH_freertos=../mtb_shared/freertos/release-v10.6.201

# Search libraries added to build
SEARCH_MTB_MK+=$(SEARCH_btstack-integration)
SEARCH_MTB_MK+=$(SEARCH_kv-store)
SEARCH_MTB_MK+=$(SEARCH_retarget-io)
SEARCH_MTB_MK+=$(SEARCH_serial-flash)
SEARCH_MTB_MK+=$(SEARCH_abstraction-rtos)
SEARCH_MTB_MK+=$(SEARCH_btstack)
SEARCH_MTB_MK+=$(SEARCH_clib-support)
SEARCH_MTB_MK+=$(SEARCH_freertos)

-include $(CY_INTERNAL_APP_PATH)/importedbsp.mk
COMPONENTS += MW_BTSTACK_INTEGRATION
COMPONENTS += MW_KV_STORE
COMPONENTS += MW_RETARGET_IO
COMPONENTS += MW_SERIAL_FLASH
COMPONENTS += MW_ABSTRACTION_RTOS
COMPONENTS += MW_BTSTACK
COMPONENTS += MW_CLIB_SUPPORT
COMPONENTS += MW_FREERTOS


#
# generate make targets for the graphical editors that are specific to this project
#

.PHONY: mtb_help_tools_start mtb_help_tools_end
